[package]
name = "oarfish-core"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
serde.workspace     = true
time.workspace      = true
blake3.workspace    = true
thiserror.workspace = true
ulid.workspace  = true
ts-rs.workspace = true
bytes.workspace = true

[dev-dependencies]
insta.workspace = true
rstest.workspace = true
serde_json.workspace = true
proptest.workspace = true
