[package]
name = "oarfish-ingest"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
oarfish-core.workspace = true
tokio.workspace        = true
tokio-stream.workspace = true
syslog_loose.workspace = true
bytes.workspace        = true
time.workspace         = true
thiserror.workspace    = true
tracing.workspace      = true
