// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subset of ITU-T X.733, because that is the vocabulary a NOC already
 * speaks.
 *
 * X.733's `indeterminate` is deliberately dropped: if oarfish cannot decide,
 * that is a confidence signal, not a severity.
 *
 * Variants are declared in escalation order so the derived `Ord` is the
 * comparison the alarm engine actually wants. Do not reorder them to match
 * the board's display order, which runs the other way.
 */
export type Severity = "cleared" | "info" | "minor" | "major" | "critical";
