// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One alarm, in the shape the board reads it.
 *
 * There is no `title` and no summary field, by design: oarfish classifies, it
 * does not narrate. The display line is the masked template, which is the same
 * artifact `Template.svelte` draws, so nothing here is generated prose.
 */
export type Alarm = { id: AlarmId, template_id: TemplateId, 
/**
 * The masked template, verbatim. The alarm's display line.
 */
template: string, severity: Severity, host: string, 
/**
 * Occurrences folded into this alarm. Exported as a TypeScript `number`
 * rather than ts-rs's default `bigint`, because it crosses the wire as a
 * JSON number.
 */
count: number, 
/**
 * `time` has no ts-rs integration, so the TypeScript type is declared by
 * hand and the wire format is pinned to RFC 3339 rather than `time`'s
 * default component encoding.
 */
opened_at: string, };

/**
 * A ULID, so the store gets chronological range scans for free.
 */
export type AlarmId = string;

/**
 * One line, normalized. The raw bytes are kept verbatim: at 3am the operator
 * wants the bytes that arrived, not our interpretation of them.
 */
export type Event = { 
/**
 * The bytes that arrived, unchanged. [`Event::raw_lossy`] converts at the
 * mask boundary; the board cannot render invalid UTF-8, so the `ts-rs`
 * export declares `string` through that same lossy conversion.
 */
raw: string, 
/**
 * Oarfish's clock, at intake. What windows order on.
 */
received_at: string, 
/**
 * What the source claimed. `None` when it claimed nothing.
 */
timestamp: string | null, 
/**
 * The sending host, or the socket peer when the frame names none.
 */
host: string, source: Source, 
/**
 * Everything source-specific: syslog severity and facility, the journal's
 * fields, OTLP attributes. `BTreeMap` for deterministic snapshots.
 */
attrs: { [key in string]: string }, };

/**
 * The blake3 hash of the canonicalised question set, truncated to 16 bytes.
 *
 * Same discipline `bundle_hash` gives masking: a fixed, short identity for
 * "what was asked", carried on every verdict so a reworded question cannot
 * silently hit an answer meant for another. Displayed and serialized as
 * 32 lowercase hex characters.
 */
export type QuestionsHash = string;

/**
 * A subset of ITU-T X.733, because that is the vocabulary a NOC already
 * speaks.
 *
 * X.733's `indeterminate` is deliberately dropped: if oarfish cannot decide,
 * that is a confidence signal, not a severity.
 *
 * Variants are declared in escalation order so the derived `Ord` is the
 * comparison the alarm engine actually wants. Do not reorder them to match
 * the board's display order, which runs the other way.
 */
export type Severity = "cleared" | "info" | "minor" | "major" | "critical";

/**
 * One variable slot in a masked template, with how often it has matched.
 *
 * This is what `Template.svelte` draws as a dimension line beneath the
 * schematic, so `pattern` is carried verbatim for display.
 */
export type Slot = { 
/**
 * The placeholder name, without decoration: `DEV` for `<VAR:DEV>`.
 */
name: string, 
/**
 * The regex that matched, as written in the bundle.
 */
pattern: string, 
/**
 * Occurrences seen. Exported as a TypeScript `number` rather than ts-rs's
 * default `bigint` for 64-bit integers, because it crosses the wire as a
 * JSON number. Counts stay far below 2^53.
 */
seen: number, };

/**
 * Where a line came from. Three listeners, no registry: these are not
 * pluggable, so this is a closed enum and not a trait.
 */
export type Source = "syslog" | "journal" | "otlp";

/**
 * The stable identity of one masked template, and the key every cached
 * verdict hangs off.
 *
 * Derived from the masked text alone, so it is reproducible from the log
 * corpus and nothing else. That is also the risk: change the mask bundle and
 * every id moves, orphaning every verdict.
 *
 * The bundle version has to be recorded alongside each cached verdict and
 * checked on read; nothing enforces that yet. Get that wrong and the failure
 * is not a cache miss, it is a false hit: if a bundle change makes one
 * template mask down to text a different template already produced, the two
 * ids collide and the store serves the wrong verdict without complaint.
 */
export type TemplateId = string;

/**
 * The cached judgment on one template.
 *
 * Stored, cached and rendered; never re-asked. Valid only for the question
 * set in [`Verdict::questions_hash`] and the build in [`Verdict::model`]:
 * the gate proved a request for `typesafe/jev-1.13` is answered by a dated
 * build, so the resolved id is recorded rather than assumed.
 */
export type Verdict = { template_id: TemplateId, questions_hash: QuestionsHash, 
/**
 * The resolved, dated model id that answered — e.g.
 * `typesafe/jev-1.13-20260917` — not the requested pin.
 */
model: string, 
/**
 * One entry per question id asked.
 */
answers: { [key in string]: VerdictAnswer }, judged_at: string, };

/**
 * One judged answer, in domain shape.
 *
 * Mirrors the wire's three primitives without naming a provider field:
 * `choice` picks one option, `score` places the state on an ordered rubric,
 * `noul` is P(yes) for a yes/no question.
 *
 * Externally tagged (the default) rather than matching the wire's
 * `{"type": ...}` shape, because the store writes `postcard` and postcard —
 * not being self-describing — only supports externally tagged enums. The
 * wire type in `oarfish-jev` keeps the provider's shape; this is the mapped
 * domain value.
 *
 * `choice` and `score` carry the full distribution plus the provider's
 * calibrated `confidence`, both required — a payload without a confidence is
 * a parse error, never a default, because a defaulted `0.0` would route as
 * "record, no surface" and silently swallow a page. `noul` carries no
 * separate confidence on the wire; its value *is* the probability, so
 * [`VerdictAnswer::confidence`] returns `None` for it rather than inventing
 * one.
 */
export type VerdictAnswer = { "choice": { choice: string, confidence: number, probabilities: { [key in string]: number }, } } | { "score": { score: number, confidence: number, probabilities: { [key in string]: number }, 
/**
 * No `skip_serializing_if`: verdicts are `postcard`-encoded for the
 * store and postcard is not self-describing, so a skipped field
 * shifts every field after it and corrupts the stream.
 */
legend: { [key in string]: string } | null, } } | { "noul": { noul: number, } };
