[package]
name = "oarfish-drain"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
oarfish-core.workspace = true
serde.workspace        = true
thiserror.workspace    = true

[dev-dependencies]
insta.workspace        = true
rstest.workspace       = true
proptest.workspace     = true
criterion.workspace    = true
oarfish-mask.workspace = true
oarfish-ingest.workspace = true
time.workspace         = true
csv.workspace          = true
regex.workspace        = true

[[bench]]
name    = "drain"
harness = false
